run_profile: "daily"
workspace: "./workspace"
filters:
  keywords: ["vulnerability", "exploit", "zero-day", "patch", "cve", "malware", "trojan", "worm", "spyware", "backdoor", "rootkit", "ransomware", "phishing", "spearphishing", "smishing", "vishing", "botnet", "ddos", "denial of service", "supply chain", "insider threat", "data breach", "exfiltration", "privilege escalation", "remote code execution", "injection", "sql injection", "xss", "csrf", "authentication bypass", "credential theft", "brute force", "password spraying", "session hijacking", "man in the middle", "mitm", "apt", "nation-state", "cyber espionage", "campaign", "threat actor", "hacktivist", "trojanized", "loader", "dropper", "keylogger", "info stealer", "data wiper"]
  cve_regex: '\bCVE-\d{4}-\d{4,7}\b'

sources:
  rss:
    - "https://thehackernews.com/feeds/posts/default"
    - "https://cyware.com/allnews/feed"
    # - "https://www.darkreading.com/rss.xml"
    - "https://krebsonsecurity.com/feed/"
    - "https://www.zdnet.com/topic/security/rss.xml"
    - "https://www.scmagazine.com/home/feed/"
    - "https://feeds.feedburner.com/eset/blog"
    - "https://securelist.com/feed/"
    - "https://psirtapi.global.sonicwall.com/api/v1/feed/rss.xml"
    - "https://research.checkpoint.com/feed/"
    - "https://unit42.paloaltonetworks.com/feed/"
    - "https://blogs.cisco.com/security/feed"
    - "https://www.mcafee.com/blogs/feed/"
    - "https://www.crowdstrike.com/blog/feed/"
    - "https://www.sans.org/blog/feed/"
    - "https://threatpost.com/feed/"
    - "https://blogs.vmware.com/security/feed/"
    - "https://www.trendmicro.com/en_us/research/rss.html"
    - "https://feeds.feedburner.com/TheHackersNews?format=xml"
    - "https://grahamcluley.com/feed/"
    - "https://isc.sans.edu/rssfeed_full.xml"
    - "https://www.schneier.com/feed/atom/"
    - "https://news.sophos.com/en-us/category/security-operations/feed/"
    - "https://news.sophos.com/en-us/category/threat-research/feed/"
    - "https://www.troyhunt.com/rss/"
    - "https://0dayfans.com/feed.rss"
    - "https://www.usom.gov.tr/rss/tehdit.rss"
    - "https://www.usom.gov.tr/rss/duyuru.rss"
    - "https://www.misp-project.org/feed.xml"
    - "https://openphish.com/feed.txt"
    - "https://feodotracker.abuse.ch/feeds/"
    - "https://github.com/thehappydinoa/awesome-threat-intel-rss"
    - "https://rss.feedspot.com/cyber_security_rss_feeds/"
    - "https://socradar.io/the-ultimate-list-of-free-and-open-source-threat-intelligence-feeds/"
    - "https://www.us-cert.gov/ncas/alerts.xml"
    - "https://www.sans.org/webcasts/rss"
    - "https://cyware.com/rss-feed/"
    - "https://feeds.feedburner.com/TheHackersNews"
    - "https://www.schneier.com/blog/atom.xml"
    - "https://isc.sans.edu/rssfeed.xml"
    - "https://www.fireeye.com/blog/threat-research/_jcr_content.feed"
    - "https://www.tripwire.com/state-of-security/feed/"
    - "https://www.infosecurity-magazine.com/rss/news/"
    - "https://cybersecurity.att.com/site/blog-all-rss"
    - "https://www.cybereason.com/blog/rss.xml"
    - "https://blog.qualys.com/feed/"
    - "https://www.tenable.com/blog/feed"
    - "https://www.blackhillsinfosec.com/feed/"
    - "https://rss.packetstormsecurity.com/files/"
    - "https://www.arbornetworks.com/blog/asert/feed/"
    - "https://www.trendmicro.com/rss/index.xml"
    - "https://www.ghacks.net/feed/"
    - "https://www.cshub.com/rss/categories/attacks"
    - "https://www.cshub.com/rss/categories/malware"
    - "https://www.cshub.com/rss/categories/threat-defense"
    - "https://www.cshub.com/rss/categories/data"
    - "https://www.schneier.com/tag/cybersecurity/feed/"
    - "https://www.csoonline.com/feed/"
    - "https://fidelissecurity.com/feed/"
    - "https://cyberbuilders.substack.com/feed"
    - "https://ventureinsecurity.net/feed"
    - "https://feeds.feedburner.com/mattpalmeroncybersecurity"
    - "https://davinciforensics.co.za/cybersecurity/feed/"
    - "https://www.techrepublic.com/rssfeeds/topic/cybersecurity/"
    - "https://www.imperva.com/blog/feed/"
    - "https://www.scnsoft.com/blog/category/information-security/atom"
    - "https://www.upguard.com/blog/rss.xml"
    - "https://blog.pcisecuritystandards.org/rss.xml"
    - "https://heimdalsecurity.com/blog/feed/"
    - "https://www.cheapsslshop.com/blog/feed"
    - "https://secureblitz.com/feed/"
    - "https://www.cyberdefensemagazine.com/feed/"
    - "https://cyberhoot.com/category/blog/feed/"
    - "https://socprime.com/feed/"
    - "https://www.pivotpointsecurity.com/feed/"
    - "https://clearnetwork.com/feed/"
    - "https://feeds.feedburner.com/GoogleOnlineSecurityBlog"
    - "https://www.blackfog.com/feed/"
    - "https://www.lastwatchdog.com/feed/"
    - "https://mazebolt.com/feed"
    - "https://any.run/cybersecurity-blog/feed/"
    - "https://www.cm-alliance.com/cybersecurity-blog/rss.xml"
    - "https://dataprivacymanager.net/feed/"
    - "https://www.idsalliance.org/feed/"
    - "https://www.exploitone.com/feed/"
    - "https://www.tsfactory.com/forums/blogs/category/infosec-digest/feed/"
    - "https://www.cyberpilot.io/cyberpilot-blog/rss.xml"
    - "https://www.ignyteplatform.com/feed/"
    - "https://www.canarytrap.com/feed/"
    - "https://www.secureblink.com/rss-feeds/threat-feed"
    - "https://www.virtru.com/blog/rss.xml"
    - "https://www.empowerelearning.com/blog/feed/"
    - "https://www.cloudbric.com/feed/"
    - "https://www.go2bsecure.com/feed/"
    - "https://www.theguardian.com/technology/data-computer-security/rss"
    - "https://personalprivacyonline.com/feed/"
    - "https://www.varutra.com/feed/"
    - "https://internetsafetybrigade.org/our-blog/f.atom"
    - "https://blogs.quickheal.com/feed/"
    - "https://blog.securityinnovation.com/rss.xml"
    - "https://blog.entersoftsecurity.com/feed/"
    - "https://itega.org/feed/"
    - "https://lynxtechnologypartners.com/blog/feed/"
    - "https://feeds.feedburner.com/ckdiii"
    - "https://blog.blackswansecurity.com/feed/"
    - "https://www.infinigate.com/uk/news-types/news-press/feed/"
    - "https://blog.zartech.net/feed/"
    - "https://www.esecurityplanet.com/feed/"
    - "https://cyberinsider.com/feed/"

  feedly:
    enabled: false
    stream_id: "user/%7C%7C%7C/category/global.all"
    FEEDLY_TOKEN: "AzvF1tlmFnsO4jbY5pWZoJR5B10DmESgdzG0Ja_hQNLl5zzp53ilhXkbMZISbBmfQXjJ7zOeROU0XRCHKS06zfs2lclcehXgz4OGUkY5flB6HJrEHPSr9rtjsO99O3d9RG3W05S8aJTQHtVf9hGpFBa6xSLuyWDTNLAN1bbP_xqkg9IoIHys6zVqKHu7xNqPsKw1OFsDXR4pSobPUGWtOUMkkQLF8clKP83Pq7xP-ithXnavMsYA82mSOr3w:feedlydev"
aws:
  region: ""
  s3_bucket: ""
  s3_prefix: ""
  sns_topic_arn: ""
ollama:
  enabled: false
  host: "http://localhost:11434"
  model: "llama3:latest"
huggingface:
  enabled: true
  # Use a real chat model supported by HF Inference
  # Use a real chat model supported by HF Inference
  #model: "deepseek-ai/deepseek-llm-7b-chat"
  #model: "facebook/bart-large-cnn"
  #model: "fdtn-ai/Foundation-Sec-1.1-8B-Instruct"
  #model: "meta-llama/Llama-3.1-8B-Instruct:cerebras" 
  #model: "microsoft/Phi-3.5-mini-instruct" 
  model: "meta-llama/Llama-3.1-8B-Instruct" 
  #model: "google/gemma-2-2b-it"
  #model: "MiniMaxAI/MiniMax-M2.1"
  
report:
  tlp: "AMBER"
  advisory_id_prefix: "SOC-TA"
  max_advisories_per_run: 1